### PR TITLE
Feature/mobile map toggling

### PR DESCRIPTION
**Pull request by isaacchansky**
Do not merge yet! 

We're almost there, but need to figure out how to handle the sidebar...

### CODE REVIEW

**Comment by mjrouser** [comment]
How's this coming?  If it's ready, we might be able to finish off 1.0 tonight!!

**Comment by WheresHJ** [comment]
LMK if you need some design feedback tonight.

**Comment by mjrouser** [comment]
Definitely!

**Comment by mjrouser** [comment]
How's this looking @isaacchansky??

**Comment by isaacchansky** [comment]
First pass is... passably functional. 

Things to do now (IMHO):
 - [ ] fix dropdowns to work well in the given space
 - [ ] Make the button to toggle the variable selector more "button-y"
 - [ ] adjust the legend to better use the limited space.
 - [ ] maybe out of scope, but figure out how to handle what is currently hovering over the map to display detailed information, on mobile.

Let me know what you think.

screen shot 2015-05-26 at 9 44 53 pm
screen shot 2015-05-26 at 9 45 19 pm

**Pull request merged**
